blank_issues_enabled: true
contact_links:
  - name: Jan Discussions
    url: https://github.com/orgs/janhq/discussions/categories/q-a
    about: Get help, discuss features & roadmap, and share your projects
