name: Publish Plugin-core Package to npmjs
on:
  push:
    branches:
      - main
    paths:
      - "plugin-core/**"
      - ".github/workflows/publish-plugin-core.yml"
      - "!plugin-core/package.json"
jobs:
  build:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: "0"
          token: ${{ secrets.PAT_SERVICE_ACCOUNT }}

      - name: Install jq
        uses: dcarbone/install-jq-action@v2.0.1

      - name: "Auto Increase package Version"
        run: |
          # Extract current version
          current_version=$(jq -r '.version' plugin-core/package.json)

          # Break the version into its components
          major_version=$(echo $current_version | cut -d "." -f 1)
          minor_version=$(echo $current_version | cut -d "." -f 2)
          patch_version=$(echo $current_version | cut -d "." -f 3)

          # Increment the patch version by one
          new_patch_version=$((patch_version+1))

          # Construct the new version
          new_version="$major_version.$minor_version.$new_patch_version"

          # Replace the old version with the new version in package.json
          jq --arg version "$new_version" '.version = $version' plugin-core/package.json > /tmp/package.json && mv /tmp/package.json plugin-core/package.json

          # Print the new version
          echo "Updated package.json version to: $new_version"

      # Setup .npmrc file to publish to npm
      - uses: actions/setup-node@v3
        with:
          node-version: "20.x"
          registry-url: "https://registry.npmjs.org"
      - run: npm install && npm run build
        working-directory: ./plugin-core
      - run: npm publish --access public
        env:
          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
        working-directory: ./plugin-core

      - name: "Commit new version to main and create tag"
        run: |
          version=$(jq -r '.version' plugin-core/package.json)
          git config --global user.email "service@jan.ai"
          git config --global user.name "Service Account"
          git add plugin-core/package.json
          git commit -m "${GITHUB_REPOSITORY}: Update tag build $version"
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.PAT_SERVICE_ACCOUNT }}" push origin HEAD:main
          git tag -a plugin-core-$version -m "${GITHUB_REPOSITORY}: Update tag build $version for plugin-core"
          git -c http.extraheader="AUTHORIZATION: bearer ${{ secrets.PAT_SERVICE_ACCOUNT }}" push origin plugin-core-$version
